### DISCUSSION TITLE
Usage of Docker image with Gitlab CI?

### DISCUSSION THREAD

**Discussion by eddybl** [python-gitlab/python-gitlab#2822] [Q&A] [answered]
I was wondering if I can use the official docker images as an `image` in a Gitlab job configuration. I tried this:

```yaml
Test:
  image: registry.gitlab.com/python-gitlab/python-gitlab:v4.4.0-slim-bullseye
  script:
    - gitlab --help
 ```

but the pipeline fails:

```
Executing "step_script" stage of the job script
Using docker image sha256:375413e02421a39fc96f8e374408cf51419e88bb63e1904d710c66d35d2c83b7 for registry.gitlab.com/python-gitlab/python-gitlab:v4.4.0-slim-bullseye with digest registry.gitlab.com/python-gitlab/python-gitlab@sha256:680adaa1ea9220b276d5e202590738d1fb19150ec3b934c41eeb6d5e1b96fabb ...
Cannot read config from file: [Errno 2] No such file or directory: 'if [ -x '
ERROR: Job failed: exit code 1
```

Or should I rather go for a default Python slim image and install the `python-gitlab` module on the fly?

**Comment by JohnVillalovos** [comment]
I think the image takes as its arguments the arguments to the `gitlab` command.

```
podman run -it registry.gitlab.com/python-gitlab/python-gitlab:v4.4.0-slim-bullseye user --help
usage: gitlab user [-h]
  list
  get
  create
  update
  delete
  block
  follow
  unfollow
  unblock
  deactivate
  activate
  approve
  reject
  ban
  unban
             ...

options:
  -h, --help            show this help message and exit

action:
  list
  get
  create
  update
  delete
  block
  follow
  unfollow
  unblock
  deactivate
  activate
  approve
  reject
  ban
  unban
                        Action to execute on the GitLab resource.
```

That is the most I have ever used the image though. So I'm not much help.

**Comment by eddybl** [comment, marked as answer]
Well, as is often the case once you write down your problem I was now able to fix it.

I was already aware that the entrypoint is most likely the issue and the official GitLab documentation explains in detail how to circumvent this problem: https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#override-the-entrypoint-of-an-image

so the solution for this case is:

```yaml
Test:
  image: 
    name: registry.gitlab.com/python-gitlab/python-gitlab:v4.4.0-slim-bullseye
    entrypoint: [""]
  script:
    - gitlab --help
```

and this then works as expected.
