### ISSUE TITLE
pipeline.jobs.list() returns empty or incomplete lists

### ISSUE THREAD

**Issue by malem-robotiq** [python-gitlab/python-gitlab#2572]
## Description of the problem, including code/CLI snippet

```python
pipelines = project.pipelines.list(iterator=True)

    for pipeline in pipelines:
        pipeline_info = pipeline.asdict()
        print(pipeline_info)
        if pipeline_info['ref'] == 'master' and pipeline_info['status'] == 'success':
            print(pipeline.jobs.list()) 
```
## Expected Behavior

prints a list of all jobs listed in https://gitlab.com/url/to/my/repo/-/pipelines/THE_PIPELINE_ID/builds

## Actual Behavior

only prints jobs flagged as manual (we have 2 jobs that are only triggered manually, once a day in our case)

I have 6 successful jobs displayed among https://gitlab.com/url/to/my/repo/-/pipelines/THE_PIPELINE_ID/builds that are not part of the list

## Specifications

we are using triggers in our gitlab-ci.yml

very rough ddescription:

```
.trigger:
  stage: build
  needs: []
  variables:
    PARENT_PIPELINE_SOURCE: $CI_PIPELINE_SOURCE
  inherit:
    variables:
      - ...
    default:
      - retry
      - interruptible
  trigger:
    strategy: depend
    forward:
      pipeline_variables: true
      yaml_variables: true

some_job:
  extends:
    - .trigger
  trigger:
    include:
      - local: .gitlab/ci/workflow.yml
      - local: some_job.yml

some_other_job:
  extends:
    - .trigger
  trigger:
    include:
      - local: .gitlab/ci/workflow.yml
      - local: some_other_job.yml
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - changes:
        - ...
    - when: manual
      allow_failure: true

```

  - python-gitlab version: 3.14
  - API version you are using (v3/v4): v4
  - Gitlab server version (or gitlab.com): gitlab.com
