### ISSUE TITLE
Automatically publish to PyPI, when new tag is created

### ISSUE THREAD

**Issue by max-wittig** [python-gitlab/python-gitlab#609]
This would simplify the deployment process for you @gpocentek 
From the [travis documentation](https://docs.travis-ci.com/user/deployment/pypi/)
```txt
travis encrypt your-password-here --add deploy.password
```

```yaml
deploy:
  provider: pypi
  user: "Your username"
  password:
    secure: "Your encrypted password"
```
