### ISSUE TITLE
cli command line arguments for url and token

### ISSUE THREAD

**Issue by rrauenza** [python-gitlab/python-gitlab#960]
(enhancement request)

What do you think of adding command line arguments to pass the url and token on the command line?  This would make integration with gitlab ci easier,

`gitlab --url https://$CI_SERVER_HOST --token $CI_JOB_TOKEN ...`

Either that, or an option to read them from the environment (or default them from the environment?)

**Comment by max-wittig** [comment]
Good idea.

**Comment by chrisoldwood** [comment]
Is this a duplicate of #893?

**Comment by nejch** [comment]
@rrauenza if you'd be OK with env variables only, this can maybe be closed as a duplicate as Chris suggests and I can try and work on #893.

Environment variables just make sense as CLI arguments would end up passing environment variables when used in CI systems anyway (which is probably what a lot of people do with this library, like your example).

There are many issues open for CLI so maybe args can be a topic for when that gets reworked.

**Comment by rrauenza** [comment]
Yeah, that sounds reasonable.

**Comment by bittner** [comment]
I would need this feature now. Where would we implement the API token? As in:

```console
curl --silent --header "Authorization: Bearer $GITLAB_API_TOKEN" ...
```

Aside, for clarification:
- Do we technically need the distinction between the [3 types of token](https://github.com/python-gitlab/python-gitlab/blob/master/gitlab/config.py#L122-L138)?
- There is now also a [project access token](https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html). Which one of the 3 tokens needs to be set in that case?

For simplicity, I'd prefer to have it like @rrauenza originally requested: A single `--token` option for everything, which overrides any value in configurations files. We probably also should cover `--username` and `--password` (with an optional value to allow interactive input), which as a side effect will make [the container entry point](https://github.com/python-gitlab/python-gitlab/blob/master/docker-entrypoint.sh) unnecessary, e.g.

```console
gitlab --url https://$CI_SERVER_HOST --token $GITLAB_API_TOKEN ...
gitlab --username $CI_DEPLOY_USER --password ...
```

I'll try to find out if we can read from the environment from within the `argparse` setup code via the defaults. To my knowledge, there is not direct way to make argparse consider environment variables (unlike [click](https://click.palletsprojects.com/en/7.x/arguments/#environment-variables)).

**Comment by nejch** [comment]
Yeah, click would make a lot more sense for this, which is why this has kind of stalled.
To make it a global option you would probably want to add them to the base parser here:
https://github.com/python-gitlab/python-gitlab/blob/265dbbdd37af88395574564aeb3fd0350288a18c/gitlab/cli.py#L81-L130

Then if those arguments are provided and valid you would need to override `from_config()` in CLI and instantiate Gitlab with the args instead:
https://github.com/python-gitlab/python-gitlab/blob/265dbbdd37af88395574564aeb3fd0350288a18c/gitlab/cli.py#L223

Feel free to give it a shot :)

> Do we technically need the distinction between the 3 types of token?

Different types of tokens send different headers to the API, so you need to distinguish this, see https://github.com/python-gitlab/python-gitlab/blob/be0afdd3e0a7d94327fc075fcc0786b95731279d/gitlab/__init__.py#L357-L375

You can get away with combining oauth and PAT like as you suggested with the bearer header instead, but I don't think it'd work for job tokens, at least according to docs. But maybe it's just not documented, should be tested.

> There is now also a project access token. Which one of the 3 tokens needs to be set in that case?

This and the upcoming group access tokens are basically just personal access tokens for project/group bot users.

In the meantime, if you use this in CI, this workaround has worked well for me:
```yaml
  before_script:
    - pip install --quiet python-gitlab
    - 'echo -e "[global]\ndefault=gitlab\n[gitlab]\nurl=$CI_SERVER_URL\nprivate_token=$API_TOKEN" > ~/.python-gitlab.cfg'
  script:
    - 'gitlab <args...>
```

or if you're not in docker:
```yaml
  before_script:
    - pip install --quiet python-gitlab
    - 'echo -e "[global]\ndefault=gitlab\n[gitlab]\nurl=$CI_SERVER_URL\nprivate_token=$API_TOKEN" > gitlab.cfg'
  script:
    # Obviously replace with `gitlab project list` for real runs. Needs a tiny fix in python-gitlab
    - 'gitlab --config-file gitlab.cfg <args...>

```
